import React from 'react';

const Body = () => {
    return (
        <div className='body-wrapper mb-5'>
            <div className='mt-5 d-flex justify-content-between align-items-center'>
                <h3 className='fw-semibold'>Home/Writing Assistant</h3>
                <div className='d-flex'>
                    <button className="primary-button me-0 me-lg-4">Save</button>
                    <button className="primary-button d-none d-lg-block">Filter</button>
                </div>
            </div>
            <div className='mt-5 row'>
                <div className='col-12 col-lg-7 p-4 richtext-container'>
                    <h5 className=''>Enter input to get<span className='text-primary'> Writing Assistant</span> </h5>
                    <div className='d-flex my-4 flex-wrap'>
                        <div className='d-flex align-items-center me-4 pb-2'>
                            <label htmlFor="cars">Words count</label>
                            <select className='select-button' id="cars" name="cars">
                                <option value="volvo">0</option>
                                <option value="saab">Saab</option>
                                <option value="fiat">Fiat</option>
                                <option value="audi">Audi</option>
                            </select>
                        </div>
                        <div className='d-flex align-items-center me-4 pb-2'>
                            <label htmlFor="cars">Promt:</label>
                            <select className='select-button' id="cars" name="cars">
                                <option value="volvo">select</option>
                                <option value="saab">Saab</option>
                                <option value="fiat">Fiat</option>
                                <option value="audi">Audi</option>
                            </select>
                        </div>
                        <div className='d-flex align-items-center pb-2'>
                            <label htmlFor="cars">Creativity:</label>
                            <select className='select-button' id="cars" name="cars">
                                <option value="volvo">select</option>
                                <option value="saab">Saab</option>
                                <option value="fiat">Fiat</option>
                                <option value="audi">Audi</option>
                            </select>
                        </div>
                    </div>
                    <div style={{ textAlign: "right", marginBottom: "0.5rem" }}>
                        <span style={{ color: "#707070", fontSize: "14px" }}>word: 00 | character: 0/250</span>
                    </div>
                    <div className='richtext-area'>
                        <div>
                            <span className='shadow-button me-2'>B</span>
                            <span className='shadow-button me-3'>I</span>
                            <span className='me-3'>hyperlink</span>
                            <span className='me-3'>text cut</span>
                            <span className='me-3'>underline</span>
                            <span className='me-3'>underline</span>
                        </div>
                        <textarea name="" id="" cols={30} rows={10}></textarea>
                    </div>
                </div>
                <div className='col-12 col-lg-5 p-4'>
                    <button style={{ width: "100%", background: "transparent linear-gradient(180deg, #0188F3 0%, #0073CF 100%) 0% 0% no-repeat padding-box" }} className='primary-button'>Write for me</button>
                    <div style={{ textAlign: "right", marginTop: "2rem" }}>
                        <span style={{ color: "red", fontSize: "14px" }}>clear</span>
                    </div>
                    <div>
                        <div className="text-container d-flex align-items-center">
                            <span className="text-primary">copy</span>
                            <p>
                                As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was
                            </p>
                        </div>
                        <div className="text-container d-flex align-items-center">
                            <span className="text-primary">copy</span>
                            <p>
                                As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a
                            </p>
                        </div>
                        <div className="text-container d-flex align-items-center">
                            <span className="text-primary">copy</span>
                            <p>
                                As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
                            </p>
                        </div>
                        <div className="text-container d-flex align-items-center">
                            <span className="text-primary">copy</span>
                            <p>
                                As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div >
    );
};

export default Body;